/* eslint-disable @next/next/no-img-element */

/**
 * Hero backdrop: a structured computational mesh deformed by an invisible
 * body. Generated by `scripts/generate-mesh.py` into
 * `public/images/field-mesh.svg` — see that file for the geometry and for why
 * it is a standalone asset rather than inline JSX (Next serialises a
 * server-rendered SVG twice, once as HTML and again in the RSC payload, which
 * cost ~11 KB gzipped per homepage load; as a file it is ~2 KB and cached).
 *
 * Purely decorative: empty alt plus aria-hidden keeps it out of the
 * accessibility tree, and pointer-events-none keeps it out of the way.
 */
export default function FieldMesh({ className = "" }: { className?: string }) {
  return (
    <img
      src="/images/field-mesh.svg"
      alt=""
      aria-hidden="true"
      width={1200}
      height={760}
      className={className}
      style={{ objectFit: "cover", objectPosition: "center" }}
    />
  );
}
